env:
  browser: false
  node: true
extends:
  - plugin:@ianwremmel/ianwremmel/modern
  - prettier
overrides:
  - files:
      - '**/*.ts'
      - '**/*.tsx'
    extends:
      - plugin:@typescript-eslint/recommended
      - prettier/@typescript-eslint
      - plugin:import/typescript
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: ./tsconfig.json
      sourceType: module
    plugins:
      - '@typescript-eslint'
    rules:
      '@typescript-eslint/ban-ts-comment': off
      '@typescript-eslint/explicit-module-boundary-types': off
parserOptions:
  sourceType: module
rules:
  compat/compat: off
  no-restricted-syntax: off
  require-jsdoc: off
