env:
  browser: false
  node: true
extends:
  - 'plugin:@ianwremmel/ianwremmel/modern'
overrides:
  - files:
      - '*.config.js'
    env:
      node: true
    parserOptions:
      sourceType: 'script'
    rules:
      strict:
        - error
        - global
  - files:
      - '**/*.spec.*'
    env:
      jest: true
    rules:
      require-jsdoc: off
  - files:
      - '**/*.ts'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: './tsconfig.json'
    rules:
      import/export: off
      import/no-unresolved: off
      no-redeclare: off
      # use as types doesn"t count as used
      no-unused-vars: off
      valid-jsdoc: off
parserOptions:
  sourceType: 'module'
rules:
  no-restricted-syntax: off
  compat/compat: off
